#creates pairs of versions using zip_keys, lists must be the same length
python:
  - 3.6 # [linux]
  - 3.7
  - 3.7
  - 3.7
  - 3.7
  - 3.8
  - 3.8
  - 3.8
  - 3.9 # [linux] 
numpy:
  - 1.15 # [linux]
  - 1.17
  - 1.18
  - 1.19
  - 1.20
  - 1.18
  - 1.19
  - 1.20
  - 1.20 # [linux]
zip_keys:
  - python
  - numpy
