package:
  name: ccpi-astra
  version: {{ environ['CIL_VERSION'] }}

build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  

test:
  requires:
    - numpy=1.15 # [py<38]
    - numpy=1.16 # [py==38]

  source_files:
    - ./Wrappers/Python/test # [win]
    - ./ccpi/test # [not win]

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover Wrappers/Python/test # [win]
    - python -m unittest discover -s ccpi/test # [not win]
    
requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - numpy >=1.15 # [py<38]
    - numpy >=1.16 # [py==38]
    - scipy<1.6
    - ccpi-framework
    - astra-toolbox==1.9.9.dev4
	
about:
  home: http://www.ccpi.ac.uk
  license:  GPLv3
  summary: 'CCPi Toolbox'
