package:
  name: cil-astra
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  path: ../../../

build:
  preserve_egg_dir: False 
  number: {{ GIT_DESCRIBE_NUMBER }}
  
test:
  source_files:
    - ./test # [win]
    - ./ccpi/test # [not win]

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover test # [win]
    - python -m unittest discover -s ccpi/test # [not win]
    
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - pip
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - cil >=21.3,<22.0
    - astra-toolbox >=1.9.9,<=2.1.0
    # the minimal version of cudatoolkit that satisfies astra-toolbox binary
    # and runs on all recent cuda runtime drivers
    - cudatoolkit>=9.0
	
about:
  home: http://www.ccpi.ac.uk/cil
  license:  GPLv3
  summary: 'Astra-Toolbox wrappers for CCPi CIL'
