package:
  name: ccpi-astra
  version: {{ environ['CIL_VERSION'] }}

build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools

  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - python
    - numpy
    - scipy
    - ccpi-framework
    - astra-toolbox
	
about:
  home: http://www.ccpi.ac.uk
  license:  GPLv3
  summary: 'CCPi Toolbox'