package:
  name: ccpi-astra
  version: {{ environ['CIL_VERSION'] }}

build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  

test:
  source_files:
    - ./Wrappers/Python/test # [win]
    - ./ccpi/test # [not win]

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover Wrappers/Python/test # [win]
    - python -m unittest discover -s ccpi/test # [not win]
    
requirements:
  build:
    - python
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - setuptools

  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - python
    - ccpi-framework
    - astra-toolbox
	
about:
  home: http://www.ccpi.ac.uk
  license:  GPLv3
  summary: 'CCPi Toolbox'
