package:
  name: cil-astra
  version: {{ environ['CIL_VERSION'] }}

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
test:
  source_files:
    - ./test # [win]
    - ./ccpi/test # [not win]

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover test # [win]
    - python -m unittest discover -s ccpi/test # [not win]
    
requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - scipy <1.6
    - cil >=20.09
    - astra-toolbox==1.9.9.dev4 # [unix]
    - astra-toolbox>=1.9.0dev # [win]
    # the minimal version of cudatoolkit that satisfies astra-toolbox binary
    # and runs on all recent cuda runtime drivers
    - cudatoolkit>=9.0 
	
about:
  home: http://www.ccpi.ac.uk/cil
  license:  GPLv3
  summary: 'Astra-Toolbox wrappers for CCPi CIL'
