package:
  name: ccpi-astra
  version: {{ environ['CIL_VERSION'] }}

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
test:
  source_files:
    - ./Wrappers/Python/test # [win]
    - ./ccpi/test # [not win]

  commands:
    - python -c "import os; print ('TESTING IN THIS DIRECTORY' , os.getcwd())"
    - python -m unittest discover Wrappers/Python/test # [win]
    - python -m unittest discover -s ccpi/test # [not win]
    
requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - scipy <1.6
    - ccpi-framework
    - astra-toolbox =1.83
	
about:
  home: http://www.ccpi.ac.uk
  license:  GPLv3
  summary: 'CCPi Toolbox'
